#!/bin/sh
for i in packages/*jar; do
  theJar=$(basename $i) 
  #echo "checking $theJar"
  for j in decompiled/*; do
  	if [ "$theJar" != "$(basename $j)" ]; then
  	 # echo "  do $j"
  	  appears=$(find $j -name "*.class" | xargs grep -f $i | wc -l)
  	  if [ "$appears" != "0" ]; then
        echo "$(basename $j) -> $theJar"
      fi
  	 # echo "      ... $appears" 
  	fi


	 
  done
done